INDUSTRY_MAPPING: dict[str, str] = {
    # Software / SaaS / Tech
    "software development": "Software Development",
    "software": "Software Development",
    "saas": "Software Development",
    "software as a service": "Software Development",
    "computer software": "Software Development",
    "it services and it consulting": "IT Services & Consulting",
    "it services & it consulting": "IT Services & Consulting",
    "information technology and services": "IT Services & Consulting",
    "information technology & services": "IT Services & Consulting",
    "technology, information and internet": "Technology & Internet",
    "technology, information and media": "Technology & Media",
    "technology, information & internet": "Technology & Internet",
    "internet": "Technology & Internet",
    "internet publishing": "Technology & Internet",
    "online and mail order retail": "E-Commerce",
    "e-commerce": "E-Commerce",
    "ecommerce": "E-Commerce",
    # AI / ML / Data
    "artificial intelligence": "Artificial Intelligence",
    "machine learning": "Artificial Intelligence",
    "ai": "Artificial Intelligence",
    "data analytics": "Data & Analytics",
    "analytics": "Data & Analytics",
    "business intelligence": "Data & Analytics",
    "big data": "Data & Analytics",
    # Cybersecurity
    "computer and network security": "Cybersecurity",
    "cybersecurity": "Cybersecurity",
    "information security": "Cybersecurity",
    "network security": "Cybersecurity",
    # Cloud / Infrastructure
    "cloud computing": "Cloud Computing",
    "managed security services": "Managed Services",
    "managed services": "Managed Services",
    # Semiconductors / Hardware
    "semiconductors": "Semiconductors",
    "semiconductor": "Semiconductors",
    "computer hardware": "Computer Hardware",
    "electronic manufacturing": "Electronics Manufacturing",
    "electrical/electronic manufacturing": "Electronics Manufacturing",
    "electrical & electronic manufacturing": "Electronics Manufacturing",
    "consumer electronics": "Consumer Electronics",
    "telecommunications": "Telecommunications",
    "wireless": "Telecommunications",
    # Aviation & Aerospace
    "aviation and aerospace component manufacturing": "Aviation & Aerospace",
    "aviation & aerospace component manufacturing": "Aviation & Aerospace",
    "aviation & aerospace": "Aviation & Aerospace",
    "aviation and aerospace": "Aviation & Aerospace",
    "aerospace": "Aviation & Aerospace",
    "airlines and aviation": "Aviation & Aerospace",
    "airlines & aviation": "Aviation & Aerospace",
    "defense and space": "Defense & Space",
    "defense & space": "Defense & Space",
    "military": "Defense & Space",
    # Finance
    "financial services": "Financial Services",
    "banking": "Banking",
    "capital markets": "Capital Markets",
    "investment banking": "Investment Banking",
    "venture capital and private equity principals": "Venture Capital & Private Equity",
    "venture capital & private equity principals": "Venture Capital & Private Equity",
    "venture capital": "Venture Capital & Private Equity",
    "private equity": "Venture Capital & Private Equity",
    "insurance": "Insurance",
    "accounting": "Accounting",
    "investment management": "Investment Management",
    "fintech": "Financial Services",
    # Healthcare
    "hospitals and health care": "Healthcare",
    "hospitals & health care": "Healthcare",
    "hospital & health care": "Healthcare",
    "healthcare": "Healthcare",
    "health care": "Healthcare",
    "medical practices": "Medical Practices",
    "medical devices": "Medical Devices",
    "biotechnology research": "Biotechnology",
    "biotechnology": "Biotechnology",
    "pharmaceutical manufacturing": "Pharmaceuticals",
    "pharmaceuticals": "Pharmaceuticals",
    "mental health care": "Mental Health",
    "wellness and fitness services": "Wellness & Fitness",
    "wellness & fitness services": "Wellness & Fitness",
    # Education
    "higher education": "Education",
    "primary and secondary education": "Education",
    "primary/secondary education": "Education",
    "education administration programs": "Education",
    "education management": "Education",
    "e-learning": "E-Learning",
    "elearning": "E-Learning",
    "online learning": "E-Learning",
    # Marketing / Advertising
    "advertising services": "Advertising & Marketing",
    "advertising": "Advertising & Marketing",
    "marketing services": "Advertising & Marketing",
    "marketing and advertising": "Advertising & Marketing",
    "marketing & advertising": "Advertising & Marketing",
    "public relations and communications services": "Public Relations",
    "public relations & communications services": "Public Relations",
    "media production": "Media Production",
    "broadcast media production and distribution": "Broadcast Media",
    # Real Estate
    "real estate": "Real Estate",
    "commercial real estate": "Real Estate",
    "real estate and mortgage": "Real Estate",
    # Construction
    "construction": "Construction",
    "civil engineering": "Civil Engineering",
    "architecture and planning": "Architecture & Planning",
    "architecture & planning": "Architecture & Planning",
    # Manufacturing
    "manufacturing": "Manufacturing",
    "industrial machinery manufacturing": "Industrial Machinery",
    "machinery manufacturing": "Industrial Machinery",
    "automation machinery manufacturing": "Industrial Automation",
    "fabricated metal products": "Metal Manufacturing",
    "plastics manufacturing": "Plastics Manufacturing",
    "chemical manufacturing": "Chemical Manufacturing",
    "food and beverage services": "Food & Beverage",
    "food & beverage services": "Food & Beverage",
    "food production": "Food & Beverage",
    # Logistics / Transport
    "transportation, logistics, supply chain and storage": "Logistics & Transportation",
    "transportation, logistics, supply chain & storage": "Logistics & Transportation",
    "trucking and railways": "Logistics & Transportation",
    "freight and logistics services": "Logistics & Transportation",
    "freight & logistics services": "Logistics & Transportation",
    "maritime transportation": "Maritime",
    "railroad equipment manufacturing": "Railroad",
    # Retail
    "retail": "Retail",
    "retail apparel and fashion": "Fashion & Apparel",
    "retail apparel & fashion": "Fashion & Apparel",
    "luxury goods and jewelry": "Luxury Goods",
    "luxury goods & jewelry": "Luxury Goods",
    # HR / Staffing
    "staffing and recruiting": "Staffing & Recruiting",
    "staffing & recruiting": "Staffing & Recruiting",
    "human resources services": "Human Resources",
    "human resources": "Human Resources",
    # Legal / Consulting
    "law practice": "Legal",
    "legal services": "Legal",
    "business consulting and services": "Business Consulting",
    "business consulting & services": "Business Consulting",
    "management consulting": "Business Consulting",
    # Non-profit / Government
    "non-profit organizations": "Non-Profit",
    "nonprofit organizations": "Non-Profit",
    "non-profit organization management": "Non-Profit",
    "government administration": "Government",
    "government relations services": "Government",
    "think tanks": "Think Tank",
    # Entertainment / Media
    "entertainment providers": "Entertainment",
    "entertainment": "Entertainment",
    "gaming": "Gaming",
    "computer games": "Gaming",
    "movies and sound recording industries": "Film & Music",
    "music": "Film & Music",
    # Other
    "environmental services": "Environmental Services",
    "renewable energy semiconductor manufacturing": "Renewable Energy",
    "renewable energy": "Renewable Energy",
    "utilities": "Utilities",
    "oil and gas": "Oil & Gas",
    "oil & gas": "Oil & Gas",
    "mining": "Mining",
    "sports and recreation instruction": "Sports & Recreation",
    "professional training and coaching": "Training & Coaching",
    "events services": "Events",
    "outsourcing and offshoring consulting": "Outsourcing & Offshoring",
    "outsourcing/offshoring": "Outsourcing & Offshoring",
    "research services": "Research",
    "nanotechnology research": "Nanotechnology",
    "design services": "Design Services",
    "graphic design": "Design Services",
    "photography": "Photography",
    "printing services": "Printing",
    "packaging and containers manufacturing": "Packaging",
    "facilities services": "Facilities Management",
    "security and investigations": "Security",
    "individual and family services": "Social Services",
    "civic and social organizations": "Civic & Social",
}
